[profile.release]
panic = 'unwind'

[workspace]
members = [
    'node/standalone',
    'node/parachain',
    'pallets/*',
    'primitives',
    'primitives/src/bridges/finality',
    'primitives/src/bridges/headers',
    'primitives/src/bridges/utils',
    'primitives/src/bridges/snowfork/*',
    'runtime/*',
]
exclude = []
