[package]
name = "pallet-circuit-portal-rpc"
version = "1.0.0-alpha.0"
authors = ["t3rn ltd. <team@t3rn.io>"]
edition = "2018"
license = "Apache-2.0"
homepage = "https://t3rn.io"
repository = "https://github.com/t3rn/t3rn/"
description = "RPC interface for the circuit portal pallet."
readme = "README.md"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
codec = { package = "parity-scale-codec", version = "2.2.0" }
jsonrpc-core = "15.0.0"
jsonrpc-core-client = "15.0.0"
jsonrpc-derive = "15.0.0"
serde_json = "1.0.59"

serde = { version = "1.0.136", features = ["derive"] }

sp-api = { git = "https://github.com/paritytech/substrate", branch = 'polkadot-v0.9.17' }
sp-blockchain = { git = "https://github.com/paritytech/substrate", branch = 'polkadot-v0.9.17' }
sp-core = { git = "https://github.com/paritytech/substrate", branch = 'polkadot-v0.9.17' }
sp-rpc = { git = "https://github.com/paritytech/substrate", branch = 'polkadot-v0.9.17' }
sp-runtime = { git = "https://github.com/paritytech/substrate", branch = 'polkadot-v0.9.17' }
t3rn-primitives = { path = "../../../primitives", default-features = false }
pallet-circuit-portal-rpc-runtime-api = { path = "runtime-api" }
